### ISSUE TITLE
Allow ability to indicate that a method is required

### ISSUE THREAD

**Issue by Singleton06** [dynamic-builder/dynamic-builder#7]
Here is what I'm thinking:

``` java
public interface Builder 
{
    @Required
    Builder hasName(boolean hasName);

    Builder age(int age);

    BuiltObject build();
}
```

Now, if the following code is executed, it would throw an IllegalStateException

``` java
// required method wasn't called, throws IllegalStateException
new DynamicBuilderFactory().createBuilderForClass(Builder.class).age(10).build(); 
```

**Comment by kansal10** [comment]
commits:
https://github.com/dynamic-builder/dynamic-builder/commit/e81142c75e0e797f7292a450b9a978ff17ff8d2e

https://github.com/dynamic-builder/dynamic-builder/commit/02f63edc471f77f850141dbf743b2810c38e7ae4

https://github.com/dynamic-builder/dynamic-builder/commit/b96c3b0f940e8416f1211a9cfac99cfd67da98a6

https://github.com/dynamic-builder/dynamic-builder/commit/de7b64dd07dd26c2f26cd32aa20911809b3f9380
